//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mhc.rc
//
#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_ABOUTBOX                    100
#define ID_APP_ABOUT					101
#define IDR_MAINFRAME                   128
#define IDD_MAINDLG                     129
#define IDD_PARAM_DLG                   201
#define IDD_FRAME_SEARCH_DLG            202
#define IDD_QJDATA_SEARCH_DLG           203
#define IDD_LOG_SEARCH_DLG              204
#define IDC_BTN_OPEN_UDP_PORT           1000
#define IDC_EDT_UDP_PORT                1001
#define IDC_EDT_ADAPTOR_IP              1002
#define IDC_EDT_ADAPTOR_PORT            1003
#define IDC_EDT_NODE_ID                 1004
#define IDC_BTN_BROADCAST_ID            1005
#define IDC_BTN_CHECK_STATUS            1006
#define IDC_BTN_NODE_REBOOT             1007
#define IDC_BTN_SEND_PARAM              1008
#define IDC_RADIO_WORK                  1009
#define IDC_RADIO_SLEEP                 1010
#define IDC_EDT_REPORT_PERIOD           1011
#define IDC_LST_DATA                    1012
#define IDC_STC_UDP_PORT_ACK            1013
#define IDC_BTN_SEND_REPORT_PERIOD      1014
#define IDC_STC_CHECK_STATUS_ACK        1015
#define IDC_STC_NODE_REBOOT_ACK         1016
#define IDC_STC_SEND_PARAM_ACK          1017
#define IDC_STC_WORK_MOD_ACK            1018
#define IDC_LIST2                       1019
#define IDC_LST_LOG                     1019
#define IDC_STC_TOTAL_PACKET_NUM        1020
#define IDC_STC_DATA_PACKET_NUM         1021
#define IDC_STC_SEND_REPORT_PERIOD_ACK  1022
#define IDC_STC_HEART_BEAT              1023
#define IDC_CHK_EVENT_MODE              1024
#define IDC_BTN_READ_PARAM              1025
#define IDC_LST_RAW_PACKET              1026
#define IDC_LST_HEART_BEAT              1027
#define IDC_EDT_ENERGYTYPE_SOIL         1027
#define IDC_STC_READ_PARAM_ACK          1028
#define IDC_EDT_ENERGYTYPE_HANG         1028
#define IDC_EDT_CHANNEL_SOIL            1029
#define IDC_STC_HEART_BEAT2             1029
#define IDC_STC_DROP_COUNT              1029
#define IDC_EDT_CHANNEL_HANG            1030
#define IDC_EDT_RIGHTLENGTH_HANG        1031
#define IDC_EDT_KURTOSIS4               1032
#define IDC_EDT_KURTOSIS8               1033
#define IDC_EDT_ENERGY4                 1033
#define IDC_EDT_LEFTLENGTH_SOIL         1034
#define IDC_EDT_KURTOSIS1               1035
#define IDC_EDT_ENERGY1                 1036
#define IDC_EDT_RIGHTLENGTH_SOIL        1038
#define IDC_EDT_KURTOSIS2               1039
#define IDC_EDT_ENERGY2                 1040
#define IDC_EDT_KURTOSIS3               1041
#define IDC_EDT_LEFTLENGTH_HANG         1042
#define IDC_LST_SENSOR_TYPE             1043
#define IDC_LST_PERIMETER_TYPE          1043
#define IDC_BTN_OK                      1044
#define IDC_BTN_CANCEL                  1045
#define IDC_EDT_SEND                    1046
#define IDC_EDT_DISTANCE_FREQUENCY      1046
#define IDC_BTN_SEND                    1047
#define IDC_EDT_ENERGY3                 1047
#define IDC_BTN_FILTER_DATA             1048
#define IDC_COMBO_DATA_ID               1049
#define IDC_BTN_CLEAR_DATA              1050
#define IDC_BTN_CLEAR_LOG               1051
#define IDC_COMBO_DATA_TYPE             1052
#define IDC_CHK_AUTOSCROLL_DATA         1053
#define IDC_BTN_FILTER_RAWDATA          1054
#define IDC_COMBO_RAWDATA_ID            1055
#define IDC_BTN_CLEAR_RAWDATA           1056
#define IDC_CHK_AUTOSCROLL_RAWDATA      1057
#define IDC_COMBO_RAWDATA_ID2           1058
#define IDC_COMBO_RAWDATA_TYPE          1058
#define IDC_COMBO_LOG_ID                1059
#define IDC_CHK_AUTOSCROLL_LOG          1060
#define IDC_COMBO_LOG_TYPE              1061
#define IDC_BTN_APPLY                   1062
#define IDC_COMBO_ID_FILTER             1063
#define IDC_COMBO_TYPE_FILTER           1064
#define IDC_COMBO_TIME_FILTER           1065
#define IDC_EDT_TIME_START              1066
#define IDC_EDT_TIME_END                1067
#define IDC_EDIT3                       1068
#define IDC_COMBO_IP                    1071
#define IDC_BTN_FRAME_FILTER            1072
#define IDC_BTN_QJDATA_FILTER           1073
#define IDC_BTN_LOG_FILTER              1074
#define IDC_LST_QJ_FILTER               1075
#define IDC_COMBO_NODE_ID               1076
#define IDC_COMBO_DATA_IP               1078
#define IDC_BTN_CLEAR_TARGET_ID         1079
#define IDC_COMBO_ADAPTOR_IP            1080
#define IDC_BTN_READ_INI                1081
#define IDC_COMBO_RAWDATA_IP            1082
#define IDC_COMBO5                      1083
#define IDC_COMBO_LOG_IP                1083
#define IDC_CHK_STRESS_TEST             1084
#define IDC_EDT_STRESS_TIME             1085
#define IDC_STC_STRESS_RET              1086
#define IDC_EDT_REPEAT_BAUD             1087
#define IDC_BTN_STOP_STRESS_TEST        1088
